# Generated by Django 5.0.4 on 2024-04-13 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('crm', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('bio', models.TextField()),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.especialidade')),
            ],
        ),
    ]
