# Generated by Django 5.0.4 on 2024-05-03 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='foto',
        ),
        migrations.AddField(
            model_name='especialidade',
            name='descricao',
            field=models.TextField(default=datetime.datetime(2024, 5, 3, 23, 52, 39, 826206, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 23, 54, 11, 938040, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
